<?php
/**
 * @file
 * A description of what your module does.
 */

/**
 * Implements hook_menu().
 */
function mailfish_menu() {
  $items = array();
  $items['node/%/subscribe'] = array(
    'title' => 'Subscribe',
    'description' => t('Subscribe to this node.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailfish_email_form', 1),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Provides the form to add an email address.
 */
function mailfish_email_form($form, $form_state, $nid = 0) {
  global $user;
  $form['email'] = array(
    '#title' => t('Email Address'),
    '#type' => 'textfield',
    '#size' => 25,
    '#description' => t('Join our mailing list'),
    '#required' => TRUE,
    '#default_value' => isset($user->mail) ? $user->mail : '',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Sign Up!'),
  );
  $form['nid'] = array(
    '#type' => 'hidden',
    '#value' => $nid,
  );
  return $form;
}

/**
 * Validation handler for mailfish_email_form
 */
function mailfish_email_form_validate($form, &$form_state) {
  $email = $form_state['value']['email'];
  if (!valid_email_address($email)) {
    $message = t('The address %email is not a valid email address. Please re-enter your address.', array('%email' => $email));
    form_set_error('email', $message);
  }
}
